name: Secrets and Environment Variables

on:
  workflow_dispatch

jobs:
  top-secret:
    runs-on: windows-latest
    env:
      MY_APP_ID: ${{ vars.APP_ID}}

    steps:
      name: Reading the env from external files
      run: |
       chmod +x ./promptGeneratorChatGPT.js
       ./imageGeneratorDallE.js
      shell: bash